<!DOCTYPE html>
<!-- Generated by pkgdown: do not edit by hand --><html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Single-species size-spectrum dynamics • mizerExperimental</title>
<!-- jquery --><script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script><!-- Bootstrap --><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.4.1/css/bootstrap.min.css" integrity="sha256-bZLfwXAP04zRMK2BjiO8iu9pf4FbLqX6zitd+tIvLhE=" crossorigin="anonymous">
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.4.1/js/bootstrap.min.js" integrity="sha256-nuL8/2cJ5NDSSwnKD8VqreErSWHtnEP9E7AySL+1ev4=" crossorigin="anonymous"></script><!-- bootstrap-toc --><link rel="stylesheet" href="../bootstrap-toc.css">
<script src="../bootstrap-toc.js"></script><!-- Font Awesome icons --><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css" integrity="sha256-mmgLkCYLUQbXn0B1SRqzHar6dCnv9oZFPEC1g1cwlkk=" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/v4-shims.min.css" integrity="sha256-wZjR52fzng1pJHwx4aV2AO3yyTOXrcDW7jBpJtTwVxw=" crossorigin="anonymous">
<!-- clipboard.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><!-- headroom.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.11.0/headroom.min.js" integrity="sha256-AsUX4SJE1+yuDu5+mAVzJbuYNPHj/WroHuZ8Ir/CkE0=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.11.0/jQuery.headroom.min.js" integrity="sha256-ZX/yNShbjqsohH1k95liqY9Gd8uOiE1S4vZc+9KQ1K4=" crossorigin="anonymous"></script><!-- pkgdown --><link href="../pkgdown.css" rel="stylesheet">
<script src="../pkgdown.js"></script><meta property="og:title" content="Single-species size-spectrum dynamics">
<meta property="og:description" content="mizerExperimental">
<!-- mathjax --><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js" integrity="sha256-nvJJv9wWKEm88qvoQl9ekL2J+k/RWIsaSScxxlsrv8k=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/config/TeX-AMS-MML_HTMLorMML.js" integrity="sha256-84DKXVJXs0/F8OTMzX4UR909+jtl4G7SPypPavF+GfA=" crossorigin="anonymous"></script><!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
</head>
<body data-spy="scroll" data-target="#toc">
    <div class="container template-article">
      <header><div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <span class="navbar-brand">
        <a class="navbar-link" href="../index.html">mizerExperimental</a>
        <span class="version label label-default" data-toggle="tooltip" data-placement="bottom" title="Released version">0.1.1.9004</span>
      </span>
    </div>

    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
<li>
  <a href="../index.html">
    <span class="fas fa fas fa-home fa-lg"></span>
     
  </a>
</li>
<li>
  <a href="../reference/index.html">Reference</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Articles
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
<li>
      <a href="../articles/single_species_size-spectrum_dynamics.html">Single-species size-spectrum dynamics</a>
    </li>
  </ul>
</li>
<li>
  <a href="../news/index.html">Changelog</a>
</li>
      </ul>
<ul class="nav navbar-nav navbar-right">
<li>
  <a href="https://github.com/sizespectrum/mizerExperimental/">
    <span class="fab fa fab fa-github fa-lg"></span>
     
  </a>
</li>
      </ul>
</div>
<!--/.nav-collapse -->
  </div>
<!--/.container -->
</div>
<!--/.navbar -->

      

      </header><script src="single_species_size-spectrum_dynamics_files/accessible-code-block-0.0.1/empty-anchor.js"></script><div class="row">
  <div class="col-md-9 contents">
    <div class="page-header toc-ignore">
      <h1 data-toc-skip>Single-species size-spectrum dynamics</h1>
                        <h4 class="author">Gustav Delius</h4>
            
      
      <small class="dont-index">Source: <a href="https://github.com/sizespectrum/mizerExperimental/blob/master/vignettes/single_species_size-spectrum_dynamics.Rmd"><code>vignettes/single_species_size-spectrum_dynamics.Rmd</code></a></small>
      <div class="hidden name"><code>single_species_size-spectrum_dynamics.Rmd</code></div>

    </div>

    
    
<div id="introduction" class="section level1">
<h1 class="hasAnchor">
<a href="#introduction" class="anchor"></a>Introduction</h1>
<p>In this tutorial you will gain an understanding of size-spectrum dynamics. To separate the size-spectrum effects from the multi-species effects, we will concentrate on a single species in this tutorial.</p>
<p>Size-spectrum dynamics describes in detail how biomass is transported through the ecosystem from small sizes to large sizes. Thus the best way to think about size-spectrum dynamics is to think of traffic on a highway, except that instead of cars travelling along the road we have fish growing along the size axis, all the way from their egg size to their asymptotic size. Occasionally a car may turn off the highway, or a fish may die. Fish can only enter the highway at the start: their egg size.</p>
<!-- For traffic, you would be interested in modelling the traffic density.
From the traffic density we can obtain the number of cars in a section of
road by multiplying the density there by the length of the section. So the
traffic density has units of cars per meter. For fish populations, we
will be interested in modelling fish density. The number of fish in a size
class is obtained by multiplying the density in that size class by the 
width of the size class. So the fish density has units of fish per gram.  -->
<p>The flow of traffic is dependent on the traffic density, which in turn is dependent on changes in the traffic velocity. High traffic density arises in sections of the road where the traffic velocity decreases. Such a decrease can lead to traffic jams. Low traffic density arises in sections where the velocity increases, as familiar when emerging on the other side of a traffic jam. Traffic jams are self-reinforcing phenomena: if there is a decrease in speed somewhere then the density of cars increases which causes a further decrease in speed, leading to an even higher density, and so on.</p>
<p>Similarly, high fish density arises in size classes where the growth rate decreases. A pronounced decrease in growth rate can lead to pronounced peaks in the fish density, similar to a traffic jam. Of course fish density is also controlled by the death rate, with a high death rate leading to a decreased fish density.</p>
<p>To be precise, fish density in a size class increases if the rate at which fish grow into the size class is larger than the rate at which they either grow out of the size class or die while they are in the size class. Thus size-spectrum dynamics is the result of the interplay between the death rate and the changes in the growth rate. For the mathematically minded, this interplay is expressed by the partial differential equation <span class="math display">\[\frac{\partial}{\partial t}N(w,t) = 
-\frac{\partial}{\partial w}\big(N(w,t)g(w,t)\big)
- \mu(w,t)\]</span> where <span class="math inline">\(N(w,t)\)</span> is the fish density at size <span class="math inline">\(w\)</span> and time <span class="math inline">\(t\)</span>, <span class="math inline">\(g(w,t)\)</span> is the growth rate of an individual of size <span class="math inline">\(w\)</span> at time <span class="math inline">\(t\)</span> and <span class="math inline">\(\mu(w,t)\)</span> is its death rate. There is no need for you to understand the mathematical notation.</p>
<p>Size-spectrum dynamics is like the traffic on a highway where cars can leave the highway (fish can die) at any point, but they can only join the highway at its beginning (fish start out at the egg size). To model the size spectrum we therefore also have to describe the rate <span class="math inline">\(R(t)\)</span> at which eggs are entering the size spectrum, i.e., the rate at which mature fish reproduce.</p>
<p>Below we will be discussing in detail what determines the death rate <span class="math inline">\(\mu(w,t)\)</span>, the growth rate <span class="math inline">\(g(w,t)\)</span> and the rate of reproduction <span class="math inline">\(R(t)\)</span>.</p>
</div>
<div id="why-study-size-spectrum-dynamics" class="section level1">
<h1 class="hasAnchor">
<a href="#why-study-size-spectrum-dynamics" class="anchor"></a>Why study size-spectrum dynamics?</h1>
<p>The study of traffic dynamics has had real practical benefits. For example, at least on motorways in Europe, when there is a danger of a traffic jam developing, automatic speed restrictions are imposed at a certain distance in front of the developing slow-moving traffic. For motorists who have not thought about traffic flow, these speed restrictions in places where there is no obvious reason for them are very annoying. However they do indeed avoid the formation of the traffic jam.</p>
<p>Of course we can not directly tell fish to obey limits to their growth rates. However we do have influence on their size-spectrum dynamics through fishing policy. For example if some species experiences stunted growth, like for example the Herring in the Baltic Sea, we could resolve that by reducing their numbers (which increases their growth rate because of reduced competition for food) or by reducing fishing on their prey.</p>
<p>The size-spectrum dynamics in a multi-species ecosystem is extremely complex. We can understand very simplified cases analytically, but in general we need to use numerical simulation to understand the consequences of various interventions.</p>
<p>The mizer package can simulate the size-specrum dynamics. Given the model parameters that enter into the expression of the growth rate, the death rate and the reproductive rate, and an initial fish size spectrum, mizer simulates the changes in the size spectrum over time according to the above equations.</p>
<p>Of particular interest is the steady state of the size spectrum, where the effects of the death rate and the changes in the growth rate exactly balance in such a way that the size spectrum stays constant over time. We will be looking both at the steady state and at time-varying size spectra below.</p>
<p>Our emphasis will be on understanding the dynamics. We do not just want to learn how to run simulations but we want to use the simulations to develop an intuition for how fish populations behave. We therefore start with very simple models first.</p>
</div>
<div id="a-first-example" class="section level1">
<h1 class="hasAnchor">
<a href="#a-first-example" class="anchor"></a>A first example</h1>
<p>Let us start by looking at an example. Start RStudio and load the following packages:</p>
<div class="sourceCode" id="cb1"><html><body><pre class="r"><span class="fu"><a href="https://rdrr.io/r/base/library.html">library</a></span>(<span class="no">mizerExperimental</span>)
<span class="fu"><a href="https://rdrr.io/r/base/library.html">library</a></span>(<span class="no">tidyverse</span>)
<span class="fu"><a href="https://rdrr.io/r/base/library.html">library</a></span>(<span class="no">plotly</span>)</pre></body></html></div>
<p>If you get error messages saying that a particular package is not available, you will need to install that package. To install the <code>mizerExperimental</code> package you would need to do</p>
<div class="sourceCode" id="cb2"><html><body><pre class="r"><span class="kw pkg">remotes</span><span class="kw ns">::</span><span class="fu"><a href="https://remotes.r-lib.org/reference/install_github.html">install_github</a></span>(<span class="st">"sizespectrum/mizerExperimental"</span>)</pre></body></html></div>
<p>The <a href="https://sizespectrum.org/mizerExperimental"><code>mizerExperimental</code></a> package contains additional mizer functionality that is not yet mature enought to be part of core mizer. Loading the <code>mizerExperimental</code> package automatically also loads the <code>mizer</code> package.</p>
<p>Mizer collects all the parameters describing a size-spectrum model into one object of class <code>MizerParams</code>. You do not need to set up this object by hand but instead there are several wrapper functions in mizer that create the object for you for various types of models, and also many functions for changing specific parameters in a model. We will use the <code><a href="../reference/newSheldonParams.html">newSheldonParams()</a></code> function to set up a model describing a single fish species living in an ecosystem whose size spectrum is given by a Sheldon power-law.</p>
<p>The <code><a href="../reference/newSheldonParams.html">newSheldonParams()</a></code> function has many arguments that allow you to specify parameters for the fish species as well as for the community, but all these arguments have default values, so we can simply call the function without specifying those arguments. We will only specify the Sheldon exponent of the background community</p>
<div class="sourceCode" id="cb3"><html><body><pre class="r"><span class="no">params</span> <span class="kw">&lt;-</span> <span class="fu"><a href="../reference/newSheldonParams.html">newSheldonParams</a></span>(<span class="kw">lambda</span> <span class="kw">=</span> <span class="fl">2.05</span>)</pre></body></html></div>
<p>The function returns a <code>MizerParams</code> object and we have assigned that to the variable <code>params</code>. We will be explaining more about this model as we go along.</p>
</div>
<div id="steady-state-spectrum" class="section level1">
<h1 class="hasAnchor">
<a href="#steady-state-spectrum" class="anchor"></a>Steady state spectrum</h1>
<p>The <code>params</code> object also contains an initial size spectrum that is close to the steady state of the model. The steady state is the state where in each size class the inflow of individuals through growth exactly balances the outflow of individuals through growth and death. If we start close to the steady state then usually if we simulate the size-spectrum dynamics for a while the population will evolve closer and closer to the steady state.</p>
<p>To get to the steady state we use the <code>steady()</code> function. The result of that function is again a MizerParams object but now with an initial size spectrum that has evolved to be very close to the steady state.</p>
<div class="sourceCode" id="cb4"><html><body><pre class="r"><span class="no">params</span> <span class="kw">&lt;-</span> <span class="fu">steady</span>(<span class="no">params</span>)</pre></body></html></div>
<pre><code>## Steady state was reached before 1.5 years.</code></pre>
<p>We can plot the size spectrum with the <code>plotSpectra()</code> function.</p>
<div class="sourceCode" id="cb6"><html><body><pre class="r"><span class="fu">plotSpectra</span>(<span class="no">params</span>, <span class="kw">power</span> <span class="kw">=</span> <span class="fl">0</span>)</pre></body></html></div>
<p><img src="single_species_size-spectrum_dynamics_files/figure-html/unnamed-chunk-5-1.png" width="700"></p>
<p>The <code>power = 0</code> argument to the <code>plotSpectra()</code> function specifies that we want to plot the number density, rather than for example the biomass density.</p>
<p>The green line represents the number density of the background community, labelled as “Resource” in the plot legend, in which our foreground species finds itself. The green line is a straight line with slope -2.05. Thus the number density is proportional to <span class="math inline">\(w^{-2.05}\)</span>.</p>
<p>The other line represents the number density of our single species, which by default is just named unimaginatively “1”. We see that it is a straight line initially, but then has a bump before declining rapidly at large sizes. We will discuss in a short while what causes that shape.</p>
<p>The initial slope of the species number density is negative, which means that there are fewer larger fish than smaller fish. That is of course understandable: some fish die while they are growing up, so there tend to be fewer fish in larger size classes.</p>
<div id="exercise-1" class="section level2">
<h2 class="hasAnchor">
<a href="#exercise-1" class="anchor"></a>Exercise 1</h2>
<p>Now it is time for you to do the first exercise to use the commands you have just learned about. For this purpose you should now open the R notebook file “exercises_single-species_size-spectrum_dynamics” and read it up to the place where it shows the first exercise. Then you put your R code for the exercise straight into the code chunks in that notebook and evaluate them there. When you are satisfied with your solution, come back to this document and continue reading.</p>
</div>
</div>
<div id="numbers" class="section level1">
<h1 class="hasAnchor">
<a href="#numbers" class="anchor"></a>Numbers</h1>
<p>While the <code>plotSpectra()</code> function gives us a plot of the number density, it would be nice if we could get at the actual numbers. The number density of the steady state is stored in the <code>params</code> object in the <code>initial_n</code> slot. This is accessed as follows:</p>
<div class="sourceCode" id="cb7"><html><body><pre class="r"><span class="no">n</span> <span class="kw">&lt;-</span> <span class="no">params</span>@<span class="kw">initial_n</span></pre></body></html></div>
<p>As you can see in the “Environment” pane in RStudio, <code>n</code> is a matrix with 1 row and 251 columns. The one row corresponds to the one species. In a multispecies model there would be one row for each species, holding the number density for that species. The 251 columns are for the number densities in each of the 251 size classes. In fact, <code>n</code> is a named array, i.e., each row and each column has names. These we can extract with the <code><a href="https://rdrr.io/r/base/dimnames.html">dimnames()</a></code> function.</p>
<div class="sourceCode" id="cb8"><html><body><pre class="r"><span class="fu"><a href="https://rdrr.io/r/base/dimnames.html">dimnames</a></span>(<span class="no">n</span>)</pre></body></html></div>
<pre><code>## $sp
## [1] "1"
## 
## $w
##   [1] "0.001"   "0.00105" "0.0011"  "0.00115" "0.0012"  "0.00126" "0.00132"
##   [8] "0.00138" "0.00145" "0.00151" "0.00158" "0.00166" "0.00174" "0.00182"
##  [15] "0.00191" "0.002"   "0.00209" "0.00219" "0.00229" "0.0024"  "0.00251"
##  [22] "0.00263" "0.00275" "0.00288" "0.00302" "0.00316" "0.00331" "0.00347"
##  [29] "0.00363" "0.0038"  "0.00398" "0.00417" "0.00437" "0.00457" "0.00479"
##  [36] "0.00501" "0.00525" "0.0055"  "0.00575" "0.00603" "0.00631" "0.00661"
##  [43] "0.00692" "0.00724" "0.00759" "0.00794" "0.00832" "0.00871" "0.00912"
##  [50] "0.00955" "0.01"    "0.0105"  "0.011"   "0.0115"  "0.012"   "0.0126" 
##  [57] "0.0132"  "0.0138"  "0.0145"  "0.0151"  "0.0158"  "0.0166"  "0.0174" 
##  [64] "0.0182"  "0.0191"  "0.02"    "0.0209"  "0.0219"  "0.0229"  "0.024"  
##  [71] "0.0251"  "0.0263"  "0.0275"  "0.0288"  "0.0302"  "0.0316"  "0.0331" 
##  [78] "0.0347"  "0.0363"  "0.038"   "0.0398"  "0.0417"  "0.0437"  "0.0457" 
##  [85] "0.0479"  "0.0501"  "0.0525"  "0.055"   "0.0575"  "0.0603"  "0.0631" 
##  [92] "0.0661"  "0.0692"  "0.0724"  "0.0759"  "0.0794"  "0.0832"  "0.0871" 
##  [99] "0.0912"  "0.0955"  "0.1"     "0.105"   "0.11"    "0.115"   "0.12"   
## [106] "0.126"   "0.132"   "0.138"   "0.145"   "0.151"   "0.158"   "0.166"  
## [113] "0.174"   "0.182"   "0.191"   "0.2"     "0.209"   "0.219"   "0.229"  
## [120] "0.24"    "0.251"   "0.263"   "0.275"   "0.288"   "0.302"   "0.316"  
## [127] "0.331"   "0.347"   "0.363"   "0.38"    "0.398"   "0.417"   "0.437"  
## [134] "0.457"   "0.479"   "0.501"   "0.525"   "0.55"    "0.575"   "0.603"  
## [141] "0.631"   "0.661"   "0.692"   "0.724"   "0.759"   "0.794"   "0.832"  
## [148] "0.871"   "0.912"   "0.955"   "1"       "1.05"    "1.1"     "1.15"   
## [155] "1.2"     "1.26"    "1.32"    "1.38"    "1.45"    "1.51"    "1.58"   
## [162] "1.66"    "1.74"    "1.82"    "1.91"    "2"       "2.09"    "2.19"   
## [169] "2.29"    "2.4"     "2.51"    "2.63"    "2.75"    "2.88"    "3.02"   
## [176] "3.16"    "3.31"    "3.47"    "3.63"    "3.8"     "3.98"    "4.17"   
## [183] "4.37"    "4.57"    "4.79"    "5.01"    "5.25"    "5.5"     "5.75"   
## [190] "6.03"    "6.31"    "6.61"    "6.92"    "7.24"    "7.59"    "7.94"   
## [197] "8.32"    "8.71"    "9.12"    "9.55"    "10"      "10.5"    "11"     
## [204] "11.5"    "12"      "12.6"    "13.2"    "13.8"    "14.5"    "15.1"   
## [211] "15.8"    "16.6"    "17.4"    "18.2"    "19.1"    "20"      "20.9"   
## [218] "21.9"    "22.9"    "24"      "25.1"    "26.3"    "27.5"    "28.8"   
## [225] "30.2"    "31.6"    "33.1"    "34.7"    "36.3"    "38"      "39.8"   
## [232] "41.7"    "43.7"    "45.7"    "47.9"    "50.1"    "52.5"    "55"     
## [239] "57.5"    "60.3"    "63.1"    "66.1"    "69.2"    "72.4"    "75.9"   
## [246] "79.4"    "83.2"    "87.1"    "91.2"    "95.5"    "100"</code></pre>
<p>The names of the columns are the weight in grams at the start of each size class. Notice how R displays long vectors by breaking them across many lines and starting each line with a number in brackets. That number is the index of the first value in that row. So for example we see that the 151st size bracket starts at 1 gram. The number density in the size class between 1 gram and 1.05 grams is</p>
<div class="sourceCode" id="cb10"><html><body><pre class="r"><span class="no">n</span>[<span class="fl">1</span>, <span class="fl">151</span>]</pre></body></html></div>
<pre><code>## [1] 0.0001862372</code></pre>
<p>It is important to realise that this is not the number of fish in the size class, but the number density. To get the number of fish we have to multiply the number by the width of the size class. Conveniently those widths are also stored in the <code>params</code> object, in the <code>dw</code> slot. So the number of fish in the 151st size class is</p>
<div class="sourceCode" id="cb12"><html><body><pre class="r">(<span class="no">n</span> * <span class="no">params</span>@<span class="kw">dw</span>)[<span class="fl">1</span>, <span class="fl">151</span>]</pre></body></html></div>
<pre><code>## [1] 8.777087e-06</code></pre>
<p>You may be surprised at the small number if you interpret it as the number of fish between 1 gram and 1.05 gram in the entire ocean. However it looks more reasonable if it is the average number per square meter of sea. For more of a discussion of this issue of workinv with numbers per area, numbers per volume or numbers for the entire system see <a href="https://sizespectrum.org/mizer/dev/reference/setParams.html#units-in-mizer" class="uri">https://sizespectrum.org/mizer/dev/reference/setParams.html#units-in-mizer</a></p>
<div id="exercise-2" class="section level2">
<h2 class="hasAnchor">
<a href="#exercise-2" class="anchor"></a>Exercise 2</h2>
<p>Go back to your exercise notebook for this tutorial and answer exercise 2 before reading on.</p>
</div>
</div>
<div id="biomass-spectra" class="section level1">
<h1 class="hasAnchor">
<a href="#biomass-spectra" class="anchor"></a>Biomass spectra</h1>
<p>Without the <code>power</code> argument (or with <code>power = 1</code> which is the default) the <code>plotSpectra()</code> function plots the biomass density as a function of size.</p>
<div class="sourceCode" id="cb14"><html><body><pre class="r"><span class="fu">plotSpectra</span>(<span class="no">params</span>)</pre></body></html></div>
<p><img src="single_species_size-spectrum_dynamics_files/figure-html/unnamed-chunk-10-1.png" width="700"></p>
<p>Now the green line representing the biomass density of the background has a slope of -1.05.</p>
<p>The initial slope of the species biomass density is negative, meaning that the biomass density decreases with size. This means that even though the individual fish of course gain biomass as they grow up, there is so much death among the larvae and juvenile fish that the total biomass of any cohort nevertheless decreases as it grows up. We will explain the reason for this later when we discuss predation mortality.</p>
<p>We can also plot the Sheldon spectrum, i.e., the biomass density as a function of the log weight instead of the weight, by supplying the argument <code>power = 2</code> to <code>plotSpectra()</code>.</p>
<div class="sourceCode" id="cb15"><html><body><pre class="r"><span class="fu">plotSpectra</span>(<span class="no">params</span>, <span class="kw">power</span> <span class="kw">=</span> <span class="fl">2</span>)</pre></body></html></div>
<p><img src="single_species_size-spectrum_dynamics_files/figure-html/unnamed-chunk-11-1.png" width="700"></p>
<p>This now shows an approximately constant biomass density as a function of log size (the slope of the green line is -0.05). The biomass density of the species as a function of log size initially increases. So if binned in logarithmically-sized bins the biomass in each bin will initially increase, until it starts decreasing close to the maximum size of the species.</p>
<p>It may have been a bit confusing that we displayed the same size spectrum in three different ways. But it is important to be aware of this because in the literature you will see all different conventions being used, so if you see a plot of a size spectrum you always need to ask yourself exactly which density is being shown.</p>
<p>We can obtain the biomass density in a size class from the number density by multiplying the number density by the weight of the individuals in the size class. Of course there is a bit of error here because not all fish in the size class have the same weight, but with the small size classes that we use in mizer, the error is not too important. So we calculate</p>
<div class="sourceCode" id="cb16"><html><body><pre class="r"><span class="no">biomass_density</span> <span class="kw">&lt;-</span> <span class="no">n</span> * <span class="no">params</span>@<span class="kw">w</span></pre></body></html></div>
<p>The total biomass in each size class we obtain by multiplying the biomass density in each size class by the width of each size class</p>
<div class="sourceCode" id="cb17"><html><body><pre class="r"><span class="no">biomass</span> <span class="kw">&lt;-</span> <span class="no">biomass_density</span> * <span class="no">params</span>@<span class="kw">dw</span></pre></body></html></div>
<p>For example the biomass of fish between 1 gram and 1.05 grams is</p>
<div class="sourceCode" id="cb18"><html><body><pre class="r"><span class="no">biomass</span>[<span class="fl">151</span>]</pre></body></html></div>
<pre><code>## [1] 8.777087e-06</code></pre>
<p>Next we will discuss the shape of the species size-spectrum in more detail.</p>
</div>
<div id="allometric-rates" class="section level1">
<h1 class="hasAnchor">
<a href="#allometric-rates" class="anchor"></a>Allometric rates</h1>
<p>The first striking feature of the species size-spectrum, in all its representations, is that for small fish (larvae and juveniles) it is given by a straight line. This due to the allometric scaling of the physiological rates. The other striking feature is the bulge at around maturity size, which we will discuss in the section on reproduction.</p>
<p>First of all, as Mariella already mentioned yesterday, the metabolic rate, i.e., the rate at which an organism expends energy on its basic metabolic needs, scales as a power of the organisms’s body size, and the power is about <span class="math inline">\(p = 3/4\)</span>.</p>
<p>Because this energy needs to be supplied by consumption of food, it is natural to assume that also the consumption rate scales allometrically with a power of 3/4. When the consumption is greater than the metabolic cost then the excess leads to growth. Hence the growth rate too scales allometrically with power <span class="math inline">\(p = 3/4\)</span>.</p>
<p>Finally, the death rate of organisms tends to scale allometrically with a power of <span class="math inline">\(p - 1 = 3/4 - 1 = -1/4\)</span>. The death rate experienced by larger individuals is smaller than that of small individuals. Again this is confirmed by many observations.</p>
<p>It is a result of the mathematics that if the growth and death rates scale allometrically with exponents <span class="math inline">\(p\)</span> and <span class="math inline">\(1-p\)</span> respectively, for some metabolic exponent <span class="math inline">\(p\)</span>, that the number density at steady state is also a power law, i.e., a straight line on the log-log plot.</p>
<p>Let us check that in our model the physiological rates are indeed power laws, at least for the small sizes. We can get the growth rate with the <code>getEGrowth()</code> function. We assign the result to a variable that we name <code>growth_rate</code>.</p>
<div class="sourceCode" id="cb20"><html><body><pre class="r"><span class="no">growth_rate</span> <span class="kw">&lt;-</span> <span class="fu">getEGrowth</span>(<span class="no">params</span>)</pre></body></html></div>
<p>You can again see in the “Environment” pane that this is a matrix with one row for the one species and 251 columns for the 251 size classes. So for example the growth rate at size 1 gram is</p>
<div class="sourceCode" id="cb21"><html><body><pre class="r"><span class="no">growth_rate</span>[<span class="fl">1</span>, <span class="fl">151</span>]</pre></body></html></div>
<pre><code>## [1] 8.40452</code></pre>
<p>(because we had seen that the 151st size class starts at 1 gram). This is the per-capita growth rate, measured in grams per year.</p>
<p>We would like to make a log-log plot of the growth rate against size to check that it gives a straight line. We will use <code>ggplot()</code> for that purpose. As you saw already yesterday, <code>ggplot()</code> likes to work with data frames instead of named matrices, so we first convert the matrix into a data frame with the <code>melt()</code> function.</p>
<div class="sourceCode" id="cb23"><html><body><pre class="r"><span class="no">growth_rate_frame</span> <span class="kw">&lt;-</span> <span class="fu">melt</span>(<span class="no">growth_rate</span>)</pre></body></html></div>
<p>You can see in the “£nvironment” pane that the new variable that we called <code>growth_rate_frame</code> is a data frame with 251 observations of 3 variables. The 251 observations correspond to the 251 size classes. The 3 variables are called</p>
<div class="sourceCode" id="cb24"><html><body><pre class="r"><span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span>(<span class="no">growth_rate_frame</span>)</pre></body></html></div>
<pre><code>## [1] "sp"    "w"     "value"</code></pre>
<p>They are the species <code>sp</code>, the size <code>w</code>, and the <code>value</code> which contains the growth_rate. This data frame we can pass to <code>ggplot()</code>, using techniques you already learned yesterday.</p>
<div class="sourceCode" id="cb26"><html><body><pre class="r"><span class="no">p</span> <span class="kw">&lt;-</span> <span class="fu">ggplot</span>(<span class="no">growth_rate_frame</span>) +
    <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="kw">x</span> <span class="kw">=</span> <span class="no">w</span>, <span class="kw">y</span> <span class="kw">=</span> <span class="no">value</span>)) +
    <span class="fu">scale_x_log10</span>() +
    <span class="fu">scale_y_log10</span>() +
    <span class="fu">labs</span>(<span class="kw">x</span> <span class="kw">=</span> <span class="st">"Weight [g]"</span>,
         <span class="kw">y</span> <span class="kw">=</span> <span class="st">"Growth rate [g/year]"</span>)
<span class="no">p</span></pre></body></html></div>
<p><img src="single_species_size-spectrum_dynamics_files/figure-html/unnamed-chunk-19-1.png" width="700"> Note how we linked the x axis to the <code>w</code> variable and the y axis to the <code>value</code> variable.</p>
<p>We see that at least up to a size of a few grams the line is straight. Let’s isolate the growth rate for those smaller sizes</p>
<div class="sourceCode" id="cb27"><html><body><pre class="r"><span class="no">g_small_fish</span> <span class="kw">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/plotly/man/reexports.html">filter</a></span>(<span class="no">growth_rate_frame</span>, <span class="no">w</span> <span class="kw">&lt;=</span> <span class="fl">10</span>)</pre></body></html></div>
<p>and fit a linear model</p>
<div class="sourceCode" id="cb28"><html><body><pre class="r"><span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span>(<span class="fu"><a href="https://rdrr.io/r/base/Log.html">log</a></span>(<span class="no">g_small_fish</span>$<span class="no">value</span>) ~ <span class="fu"><a href="https://rdrr.io/r/base/Log.html">log</a></span>(<span class="no">g_small_fish</span>$<span class="no">w</span>))</pre></body></html></div>
<pre><code>## 
## Call:
## lm(formula = log(g_small_fish$value) ~ log(g_small_fish$w))
## 
## Coefficients:
##         (Intercept)  log(g_small_fish$w)  
##               2.129                0.750</code></pre>
<p>The slope of the line is indeed 0.75 = 3/4. In fact, the above shows that for juveniles <span class="math display">\[\log(g(w)) = 2.129 + \frac34 \log(w)\]</span> and thus <span class="math display">\[g(w) = g_0\ w^p = 2.129\  w^{3/4}.\]</span></p>
<p>Of course in a real model, the growth rate would not so exactly follow a power law, due to variations in the growth rate due to variations in food availability, for example.</p>
<div id="exercise-3" class="section level2">
<h2 class="hasAnchor">
<a href="#exercise-3" class="anchor"></a>Exercise 3</h2>
<p>Now over to you. Do exercise 3 in the exercise notebook. Use the methods you have just seen to make a log-log plot of the mortality rate. You can get the mortality rate with the <code>getMort()</code> function. Then fit a linear model and thus determine that the mortality rate is <span class="math display">\[\mu(w) = \mu_0\ w^{p-1} = 1.909\ w^{-1/4}.\]</span></p>
</div>
</div>
<div id="slope-of-juvenile-spectrum" class="section level1">
<h1 class="hasAnchor">
<a href="#slope-of-juvenile-spectrum" class="anchor"></a>Slope of juvenile spectrum</h1>
<p>We have seen that for juvenile fish the growth rate and the death rate are both power laws with exponents <span class="math inline">\(p=3/4\)</span> and <span class="math inline">\(p-1=-1/4\)</span> respectively and then by solving a differential equation we can derive that the juvenile spectum also follows a power law: <span class="math display">\[N(w) = N_0\ w^{-\mu_0/g_0 - p}\]</span></p>
<p>I can’t do the maths with you (and you probably don’t want me to anyway), but we can check this claim numerically. Let’s look at the spectrum up to 10 grams. By now we know how to do this. We first convert the number density matrix <code>n</code> into a dataframe and then filter out all observations that do not have <span class="math inline">\(w\leq 10\)</span>. The resulting data frame we pass to <code>ggplot()</code> and ask it to plot a line on log-log axes.</p>
<div class="sourceCode" id="cb30"><html><body><pre class="r"><span class="no">nf</span> <span class="kw">&lt;-</span> <span class="fu">melt</span>(<span class="no">n</span>) <span class="kw">%&gt;%</span>
  <span class="fu"><a href="https://rdrr.io/pkg/plotly/man/reexports.html">filter</a></span>(<span class="no">w</span> <span class="kw">&lt;=</span> <span class="fl">10</span>)

<span class="fu">ggplot</span>(<span class="no">nf</span>) +
  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="kw">x</span> <span class="kw">=</span> <span class="no">w</span>, <span class="kw">y</span> <span class="kw">=</span> <span class="no">value</span>)) +
  <span class="fu">scale_x_log10</span>() +
  <span class="fu">scale_y_log10</span>() +
  <span class="fu">labs</span>(<span class="kw">x</span> <span class="kw">=</span> <span class="st">"Weight [g]"</span>,
       <span class="kw">y</span> <span class="kw">=</span> <span class="st">"Number density [1/g]"</span>)</pre></body></html></div>
<p><img src="single_species_size-spectrum_dynamics_files/figure-html/unnamed-chunk-22-1.png" width="700"></p>
<p>That confirms what we had seen earlier, that for fish less than 10 grams the number density is a power law. To determine the exponent of the power law we need the slope of that straight line in the log-log plot, and the easiest way to do that is to fit a linear model to the log variables:</p>
<div class="sourceCode" id="cb31"><html><body><pre class="r"><span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span>(<span class="fu"><a href="https://rdrr.io/r/base/Log.html">log</a></span>(<span class="no">nf</span>$<span class="no">value</span>) ~ <span class="fu"><a href="https://rdrr.io/r/base/Log.html">log</a></span>(<span class="no">nf</span>$<span class="no">w</span>))</pre></body></html></div>
<pre><code>## 
## Call:
## lm(formula = log(nf$value) ~ log(nf$w))
## 
## Coefficients:
## (Intercept)    log(nf$w)  
##      -8.588       -1.555</code></pre>
<p>The mathematics claimed that the exponent should be <span class="math inline">\(-\mu_0 / g_0 - p\)</span>. We have already observed that <span class="math inline">\(\mu_0 = 1.909\)</span> and <span class="math inline">\(g_0 = 2.129\)</span> so we get</p>
<div class="sourceCode" id="cb33"><html><body><pre class="r">-<span class="fl">1.909</span> / <span class="fl">2.129</span> - <span class="fl">3</span>/<span class="fl">4</span></pre></body></html></div>
<pre><code>## [1] -1.646665</code></pre>
<p>That is not quite the result of the linear model fit, but that is the nature of numerical calculations: one gets discretisation errors and rounding errors.</p>
</div>
<div id="reproduction" class="section level1">
<h1 class="hasAnchor">
<a href="#reproduction" class="anchor"></a>Reproduction</h1>
<p>Now that we understand the shape of the size spectrum for the juvenile fish, let us try to understand the bulge that follows. The increase of abundance that we see at around the maturity size of our species is due to a drop in growth rate at that size. This in turn is due to the fact that the mature fish invests some of its energy income into reproduction.</p>
<p>The proportion of the available energy that is invested into reproduction is stored in the <code>psi</code> slot of the <code>params</code> object. As so many of the other quantities in mizer, it is a matrix with one row for each species and once column for each size class. So we can plot it by melting the matrix into a data frame and then using this in <code>ggplot()</code>.</p>
<div class="sourceCode" id="cb35"><html><body><pre class="r"><span class="fu">ggplot</span>(<span class="fu">melt</span>(<span class="no">params</span>@<span class="kw">psi</span>)) +
  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="kw">x</span> <span class="kw">=</span> <span class="no">w</span>, <span class="kw">y</span> <span class="kw">=</span> <span class="no">value</span>))</pre></body></html></div>
<p><img src="single_species_size-spectrum_dynamics_files/figure-html/unnamed-chunk-25-1.png" width="700"></p>
<p>How was this maturity curve specified? There are four species parameters involved: * the maturity size <code>w_mat</code> at which 50% of the individuals are mature. * the size <code>w_mat25</code> at wich 25% of the individuals are mature. * the asymptotic size <code>w_inf</code> at which an organism invests 100% of its income into reproduction and thus growth is zero. * an exponent <code>m</code> that determines how the proportion that an individual invests into reproduction scales with its size.</p>
<p>Such species parameters are contained in the <code>species_params</code> slot of the <code>params</code> object.</p>
<div class="sourceCode" id="cb36"><html><body><pre class="r"><span class="no">params</span>@<span class="kw">species_params</span></pre></body></html></div>
<pre><code>##   species w_min w_inf    w_mat w_min_idx k_vb ks beta sigma z0 alpha    erepro
## 1       1 0.001   100 25.11886         1    1  4  100   1.3  0   0.4 0.2036643
##   interaction_resource    n    p   q pred_kernel_type       h k    gamma
## 1                    1 0.75 0.75 0.8        lognormal 51.6855 0 3686.147
##    w_mat25 m    R_max constant_reproduction
## 1 22.50546 1 1.692216             0.4230541</code></pre>
<p>As you can see, there are a lot of other species parameters, some of which we will talk about later. For now let’s just select the 4 parameters we are interested in.</p>
<div class="sourceCode" id="cb38"><html><body><pre class="r"><span class="fu"><a href="https://rdrr.io/pkg/plotly/man/reexports.html">select</a></span>(<span class="no">params</span>@<span class="kw">species_params</span>, <span class="no">w_mat</span>, <span class="no">w_mat25</span>, <span class="no">w_inf</span>, <span class="no">m</span>)</pre></body></html></div>
<pre><code>##      w_mat  w_mat25 w_inf m
## 1 25.11886 22.50546   100 1</code></pre>
<div id="effect-of-change-in-maturity-curve" class="section level2">
<h2 class="hasAnchor">
<a href="#effect-of-change-in-maturity-curve" class="anchor"></a>Effect of change in maturity curve</h2>
<p>Let us investigate what happens when we change the maturity curve. Let’s assume the maturity size is actually 40 grams and the size at which 25% of individuals is mature is 30 grams. Let us change the values in the <code>species_params</code> data frame. But first we make a copy of the params object so that we can keep the old version around unchanged.</p>
<div class="sourceCode" id="cb40"><html><body><pre class="r"><span class="no">params_changed_maturity</span> <span class="kw">&lt;-</span> <span class="no">params</span></pre></body></html></div>
<p>In this copy we now change the species paramters</p>
<div class="sourceCode" id="cb41"><html><body><pre class="r"><span class="no">params_changed_maturity</span>@<span class="kw">species_params</span>$<span class="no">w_mat</span> <span class="kw">&lt;-</span> <span class="fl">40</span>
<span class="no">params_changed_maturity</span>@<span class="kw">species_params</span>$<span class="no">w_mat25</span> <span class="kw">&lt;-</span> <span class="fl">30</span>
<span class="fu"><a href="https://rdrr.io/pkg/plotly/man/reexports.html">select</a></span>(<span class="no">params_changed_maturity</span>@<span class="kw">species_params</span>, <span class="no">w_mat</span>, <span class="no">w_mat25</span>, <span class="no">w_inf</span>, <span class="no">m</span>)</pre></body></html></div>
<pre><code>##   w_mat w_mat25 w_inf m
## 1    40      30   100 1</code></pre>
<p>This has not yet changed the <code>params@psi</code> slot in the <code>params</code> object yet. For that we need to call the <code>setReproduction()</code> function.</p>
<div class="sourceCode" id="cb43"><html><body><pre class="r"><span class="no">params_changed_maturity</span> <span class="kw">&lt;-</span> <span class="fu">setReproduction</span>(<span class="no">params_changed_maturity</span>)</pre></body></html></div>
<p>Now the maturity curve has changed, which we can verify by plotting it</p>
<div class="sourceCode" id="cb44"><html><body><pre class="r"><span class="fu">ggplot</span>(<span class="fu">melt</span>(<span class="no">params_changed_maturity</span>@<span class="kw">psi</span>)) +
  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="kw">x</span> <span class="kw">=</span> <span class="no">w</span>, <span class="kw">y</span> <span class="kw">=</span> <span class="no">value</span>))</pre></body></html></div>
<p><img src="single_species_size-spectrum_dynamics_files/figure-html/unnamed-chunk-31-1.png" width="700"></p>
<p>At this point let’s take a little break and learn how to draw two curves in the same graph. How can we see the old maturity curve and the new maturity curve in the same plot? First we create the data frames we would need for the separate plots</p>
<div class="sourceCode" id="cb45"><html><body><pre class="r"><span class="no">psif</span> <span class="kw">&lt;-</span> <span class="fu">melt</span>(<span class="no">params</span>@<span class="kw">psi</span>)
<span class="no">psif_changed_maturity</span> <span class="kw">&lt;-</span> <span class="fu">melt</span>(<span class="no">params_changed_maturity</span>@<span class="kw">psi</span>)</pre></body></html></div>
<p>Then we add an extra column to each dataframe describing it</p>
<div class="sourceCode" id="cb46"><html><body><pre class="r"><span class="no">psif</span>$<span class="no">type</span> <span class="kw">=</span> <span class="st">"original"</span>
<span class="no">psif_changed_maturity</span>$<span class="no">type</span> <span class="kw">=</span> <span class="st">"changed"</span></pre></body></html></div>
<p>Then we bind the two data frames together</p>
<div class="sourceCode" id="cb47"><html><body><pre class="r"><span class="no">psif_combined</span> <span class="kw">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/cbind.html">rbind</a></span>(<span class="no">psif</span>, <span class="no">psif_changed_maturity</span>)</pre></body></html></div>
<p>and send that combined data frame to <code>ggplot()</code></p>
<div class="sourceCode" id="cb48"><html><body><pre class="r"><span class="fu">ggplot</span>(<span class="no">psif_combined</span>) +
  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="kw">x</span> <span class="kw">=</span> <span class="no">w</span>, <span class="kw">y</span> <span class="kw">=</span> <span class="no">value</span>, <span class="kw">colour</span> <span class="kw">=</span> <span class="no">type</span>))</pre></body></html></div>
<p><img src="single_species_size-spectrum_dynamics_files/figure-html/unnamed-chunk-35-1.png" width="700"></p>
<p>This change in the maturity curve of course implies a change in the growth rates.</p>
</div>
<div id="exercise-4" class="section level2">
<h2 class="hasAnchor">
<a href="#exercise-4" class="anchor"></a>Exercise 4</h2>
<p>Make a plot showing the growth rates of the original model and of the model with the changed maturity curve.</p>
<p>Next let us look how the steady state spectrum has changed. We first need to run the changed model to steady state</p>
<div class="sourceCode" id="cb49"><html><body><pre class="r"><span class="no">params_changed_maturity</span> <span class="kw">&lt;-</span> <span class="fu">steady</span>(<span class="no">params_changed_maturity</span>)</pre></body></html></div>
<pre><code>## Steady state was reached before 6 years.</code></pre>
<p>We use the same technique as above to plot the steady-state spectra of both models on top of each other.</p>
<div class="sourceCode" id="cb51"><html><body><pre class="r"><span class="no">nf</span> <span class="kw">&lt;-</span> <span class="fu">melt</span>(<span class="no">params</span>@<span class="kw">initial_n</span>)
<span class="no">nf_changed_maturity</span> <span class="kw">&lt;-</span> <span class="fu">melt</span>(<span class="no">params_changed_maturity</span>@<span class="kw">initial_n</span>)
<span class="no">nf</span>$<span class="no">type</span> <span class="kw">&lt;-</span> <span class="st">"original"</span>
<span class="no">nf_changed_maturity</span>$<span class="no">type</span> <span class="kw">&lt;-</span> <span class="st">"changed"</span>
<span class="no">nf_combined</span> <span class="kw">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/cbind.html">rbind</a></span>(<span class="no">nf</span>, <span class="no">nf_changed_maturity</span>)
<span class="fu">ggplot</span>(<span class="no">nf_combined</span>) +
  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="kw">x</span> <span class="kw">=</span> <span class="no">w</span>, <span class="kw">y</span> <span class="kw">=</span> <span class="no">value</span>, <span class="kw">colour</span> <span class="kw">=</span> <span class="no">type</span>)) +
  <span class="fu">scale_x_log10</span>() +
  <span class="fu">scale_y_log10</span>() +
  <span class="fu">labs</span>(<span class="kw">x</span> <span class="kw">=</span> <span class="st">"Weight [g]"</span>,
       <span class="kw">y</span> <span class="kw">=</span> <span class="st">"Number density [1/g]"</span>)</pre></body></html></div>
<p><img src="single_species_size-spectrum_dynamics_files/figure-html/unnamed-chunk-37-1.png" width="700"></p>
<p>As expected, the bump happens later due to the larger maturity size and it is less pronounced, because the maturity curve is less steep.</p>
</div>
<div id="reproductive-efficiency" class="section level2">
<h2 class="hasAnchor">
<a href="#reproductive-efficiency" class="anchor"></a>Reproductive efficiency</h2>
<p>So what happens with the energy that is invested into reproduction? It leads to spawning and thus the influx of new individuals at the egg size. This conversion of energy invested into reproduction into egg biomass is inefficient. Firstly much energy is spent on things like migration to spawning grounds, rather than on production of gonadic mass. Secondly, only a small proportion of eggs that are produced are viable and hatch into larvae.</p>
<p>In fact, in order for the population to be at steady state, the reproductive efficiency has to have a particular value. If it were higher, the population would increase, if it was lower, the population would decrease with time. The <code>steady()</code> function has set the reproductive efficiency to just the right value and has stored it in the <code>erepro</code> species parameter.</p>
<div class="sourceCode" id="cb52"><html><body><pre class="r"><span class="no">params</span>@<span class="kw">species_params</span>$<span class="no">erepro</span></pre></body></html></div>
<pre><code>## [1] 0.2036643</code></pre>
<p>The model with the changed maturity curve leads to a different rate of investment into reproduction and thus needs a slightly different reproductive efficiency to remain at steady state:</p>
<div class="sourceCode" id="cb54"><html><body><pre class="r"><span class="no">params_changed_maturity</span>@<span class="kw">species_params</span>$<span class="no">erepro</span></pre></body></html></div>
<pre><code>## [1] 0.1915709</code></pre>
<p>This is the reproductive efficiency at steady state. When the population deviates from the steady state, for example due to a change in fishing, the reproductive efficiency can be set to change according to a Beverton-Holt stock-recruitment curve. We will discuss this again later.</p>
</div>
</div>
<div id="effect-of-decreased-prey-availability" class="section level1">
<h1 class="hasAnchor">
<a href="#effect-of-decreased-prey-availability" class="anchor"></a>Effect of decreased prey availability</h1>
<p>The energy income for a fish comes from predation on its prey. If there is less prey, the fish consumes less and thus its growth rate will decrease. Let us investigate this by artificially removing some prey.</p>
<p>Below we decrease the community spectrum by a factor of 10 in the size range from 1mg to 10mg. We again create a new parameter object to be able to keep the old one around</p>
<div class="sourceCode" id="cb56"><html><body><pre class="r"><span class="no">params_starved</span> <span class="kw">&lt;-</span> <span class="no">params</span>
<span class="no">size_range</span> <span class="kw">&lt;-</span> <span class="no">params</span>@<span class="kw">w_full</span> <span class="kw">&gt;</span> <span class="fl">10</span>^-<span class="fl">3</span> <span class="kw">&amp;</span> <span class="no">params</span>@<span class="kw">w_full</span> <span class="kw">&lt;</span> <span class="fl">10</span>^-<span class="fl">2</span>
<span class="no">params_starved</span>@<span class="kw">initial_n_pp</span>[<span class="no">size_range</span>] <span class="kw">&lt;-</span> <span class="no">params</span>@<span class="kw">initial_n_pp</span>[<span class="no">size_range</span>] / <span class="fl">10</span>
<span class="fu">plotSpectra</span>(<span class="no">params_starved</span>)</pre></body></html></div>
<p><img src="single_species_size-spectrum_dynamics_files/figure-html/unnamed-chunk-40-1.png" width="700"></p>
<p>That is of course quite a dramatic intervention, and so should allow us to clearly see its effect on the steady-state size distribution of our species.</p>
<div class="sourceCode" id="cb57"><html><body><pre class="r"><span class="no">params_starved</span> <span class="kw">&lt;-</span> <span class="fu">steady</span>(<span class="no">params_starved</span>)</pre></body></html></div>
<pre><code>## Steady state was reached before 6 years.</code></pre>
<div class="sourceCode" id="cb59"><html><body><pre class="r"><span class="fu">plotSpectra</span>(<span class="no">params_starved</span>, <span class="kw">power</span> <span class="kw">=</span> <span class="fl">2</span>)</pre></body></html></div>
<p><img src="single_species_size-spectrum_dynamics_files/figure-html/unnamed-chunk-42-1.png" width="700"></p>
<p>As expected, the lack of food and the resulting slow-down in growth leads to a traffic jam: a peak in the biomass density. This slow-down occurs at a size that is about a factor of 100 larger than the size at which food is reduced. Why this is we will discuss in the next section. But first investigate what happens when the prey abundance is increased instead of decreased.</p>
<div id="exercise-5" class="section level2">
<h2 class="hasAnchor">
<a href="#exercise-5" class="anchor"></a>Exercise 5</h2>
<p>Plot the steady state biomass density in our model when the community abundance is increased by a factor of 10 in the size range from 1mg to 10mg.</p>
</div>
</div>
<div id="predation" class="section level1">
<h1 class="hasAnchor">
<a href="#predation" class="anchor"></a>Predation</h1>
<p>It is now time to discuss the important issue of predation. It is through predation that the fish obtains the energy it needs to maintain its metabolism, to grow and to invest in reproduction. So it is important how we model this predation.</p>
<p>The easiest case in which to understand predation is to imagine a filter feeding fish, swimming around with its mouth open. Clearly the amount of food it takes in is determined by four things:</p>
<ul>
<li>the density of prey in the water,</li>
<li>how much volume of water the fish is able to filter, which will depend on how fast it swims as well as on its gape size.</li>
<li>what part of this prey the fish is able to filter out of the water, which will be limited by its gape size and by how fine its gill rakers are,</li>
<li>how fast it can digest the food. If it can filter the prey faster than it can digest, it will have to start letting prey go uneaten.</li>
</ul>
<p>For a more active hunter the situation will be similar. The rate at which it predates will depend on four things:</p>
<ul>
<li>the density of prey in the water</li>
<li>the volume of water that the fish patrols and in which it will be able to seek out its prey. This may depend on things like radius of vision.</li>
<li>which of this detected prey the fish is able to catch, which will depend on its mouth size but also on its agility and skill as well as on the defensive mechanisms of the prey.</li>
<li>how fast it can digest the food.</li>
</ul>
<p>Of these four factors, we have of course already been discussing the density of prey. In the next section we will discuss the ability to filter out or catch prey of particular sizes, which we model via the predation kernel. In the section after that we will discuss the search volume and then in the following section the maximum consumption rate.</p>
<div id="the-predation-kernel" class="section level2">
<h2 class="hasAnchor">
<a href="#the-predation-kernel" class="anchor"></a>The predation kernel</h2>
<p>Fish will be particularly good at catching prey in a specific range of sizes, smaller than themselves. This is encoded in the size-spectrum model by the predation kernel. Let us take a look at the predation kernel in our model. We can obtain it with the function <code>getPredKernel()</code>.</p>
<div class="sourceCode" id="cb60"><html><body><pre class="r"><span class="no">pred_kernel</span> <span class="kw">&lt;-</span> <span class="fu">getPredKernel</span>(<span class="no">params</span>)</pre></body></html></div>
<p>This is a large three-dimensional array (predator species x predator size x prey size). We extract the kernel of a predator of size 10g (using that we remember that this is in size class 201)</p>
<div class="sourceCode" id="cb61"><html><body><pre class="r"><span class="no">pred_kernel_10</span> <span class="kw">&lt;-</span> <span class="no">pred_kernel</span>[, <span class="fl">201</span>, , <span class="kw">drop</span> <span class="kw">=</span> <span class="fl">FALSE</span>]</pre></body></html></div>
<p>The <code>drop = FALSE</code> option is there to prevent R from dropping any of the array dimensions. We can now plot this as usual</p>
<div class="sourceCode" id="cb62"><html><body><pre class="r"><span class="fu">ggplot</span>(<span class="fu">melt</span>(<span class="no">pred_kernel_10</span>)) +
  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="kw">x</span> <span class="kw">=</span> <span class="no">w_prey</span>, <span class="kw">y</span> <span class="kw">=</span> <span class="no">value</span>)) +
  <span class="fu">scale_x_log10</span>()</pre></body></html></div>
<p><img src="single_species_size-spectrum_dynamics_files/figure-html/unnamed-chunk-45-1.png" width="700"></p>
<p>We see that the predator of size 10g likes to feed on prey that is about a factor 100 smaller than itself, but also feeds on other sizes, just with reduced preference. The preferred predator/prey size ratio is determined by the species parameter <code>beta</code> and the width of the feeding kernel, i.e., how fussy the predator is regarding their prey size, is determined by the species parameter <code>sigma</code>. In our model these have the values</p>
<div class="sourceCode" id="cb63"><html><body><pre class="r"><span class="fu"><a href="https://rdrr.io/pkg/plotly/man/reexports.html">select</a></span>(<span class="no">params</span>@<span class="kw">species_params</span>, <span class="no">beta</span>, <span class="no">sigma</span>)</pre></body></html></div>
<pre><code>##   beta sigma
## 1  100   1.3</code></pre>
<p>Let us change the preferred predator/prey mass ratio from 100 to 1000. As usual, we first create a copy of the parameter object before making changes. After changing the species parameters we have to call <code>setPredKernel()</code> to actually change the predation kernel in the model. Then, after changing the predation kernel, we have to determine the new steady state with <code>steady()</code>. Finally we plot the resulting spectrum.</p>
<div class="sourceCode" id="cb65"><html><body><pre class="r"><span class="no">params_pk</span> <span class="kw">&lt;-</span> <span class="no">params</span>
<span class="no">params_pk</span>@<span class="kw">species_params</span>$<span class="no">beta</span> <span class="kw">&lt;-</span> <span class="fl">1000</span>
<span class="no">params_pk</span> <span class="kw">&lt;-</span> <span class="fu">setPredKernel</span>(<span class="no">params_pk</span>)</pre></body></html></div>
<p>Let’s make a plot to see that the predation kernel has indeed changed.</p>
<div class="sourceCode" id="cb66"><html><body><pre class="r"><span class="fu">getPredKernel</span>(<span class="no">params_pk</span>)[, <span class="fl">201</span>, , <span class="kw">drop</span> <span class="kw">=</span> <span class="fl">FALSE</span>] <span class="kw">%&gt;%</span>
  <span class="fu">melt</span>() <span class="kw">%&gt;%</span>
  <span class="fu">ggplot</span>() +
  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="kw">x</span> <span class="kw">=</span> <span class="no">w_prey</span>, <span class="kw">y</span> <span class="kw">=</span> <span class="no">value</span>)) +
  <span class="fu">scale_x_log10</span>()</pre></body></html></div>
<p><img src="single_species_size-spectrum_dynamics_files/figure-html/unnamed-chunk-48-1.png" width="700"></p>
<p>If we now again reduce the prey in the size range from 1mg to 10mg as before, we now expect this to produce a peak in the biomass spectrum somewhere between 1g and 10g. Let’s check.</p>
<div class="sourceCode" id="cb67"><html><body><pre class="r"><span class="no">params_pk</span>@<span class="kw">initial_n_pp</span> <span class="kw">&lt;-</span> <span class="no">params_starved</span>@<span class="kw">initial_n_pp</span>
<span class="no">params_pk</span> <span class="kw">&lt;-</span> <span class="fu">steady</span>(<span class="no">params_pk</span>)</pre></body></html></div>
<pre><code>## Steady state was reached before 4.5 years.</code></pre>
<div class="sourceCode" id="cb69"><html><body><pre class="r"><span class="fu">plotSpectra</span>(<span class="no">params_pk</span>, <span class="kw">power</span> <span class="kw">=</span> <span class="fl">2</span>)</pre></body></html></div>
<p><img src="single_species_size-spectrum_dynamics_files/figure-html/unnamed-chunk-49-1.png" width="700"></p>
<p>Yes, as expected.</p>
<p>For details of how <code>beta</code> and <code>sigma</code> parametrise the predation kernel, see <a href="https://sizespectrum.org/mizer/dev/reference/lognormal_pred_kernel.html#details" class="uri">https://sizespectrum.org/mizer/dev/reference/lognormal_pred_kernel.html#details</a>. For information on how to change the predation kernel, see <a href="https://sizespectrum.org/mizer/dev/reference/setPredKernel.html#setting-predation-kernel" class="uri">https://sizespectrum.org/mizer/dev/reference/setPredKernel.html#setting-predation-kernel</a></p>
<p>It is very important not to confuse the prey preference with the diet. Just because a predator might prefer to feed on prey of a particular size if it had free choice does not mean that it actually feeds predominantly on such prey. The actual diet of the fish depends also on the availability of prey. Because smaller prey are more abundant, the realised predator/prey mass ratio in the diet will be smaller than the preferred predator/prey mass ratio. This is particularly important when estimating the predation kernel from stomach data.</p>
</div>
<div id="exercise-6" class="section level2">
<h2 class="hasAnchor">
<a href="#exercise-6" class="anchor"></a>Exercise 6</h2>
<p>This exercise gives you a different set of predation kernel parameters to investigate.</p>
</div>
<div id="search-volume" class="section level2">
<h2 class="hasAnchor">
<a href="#search-volume" class="anchor"></a>Search volume</h2>
<p>Next we consider the factor that models the volume of water a filter feeder is able to filter in a certain amount of time, or the volume of water a forage fish is able to patrol in a certain amount of time. This is difficult to model fron first principles, although people have tried to argue in terms of swimming speeds of fish. We will simply assume that this search volume rate is also an allometric rate. Let <span class="math inline">\(\gamma(w)\)</span> denote this rate for a predator of size <span class="math inline">\(w\)</span>. The we assume that <span class="math display">\[\gamma(w) = \gamma_0\ w^q\]</span> for some exponent <span class="math inline">\(q\)</span>. We know that a fish needs to consume prey at a rate that scales with its body size to the power p, with p about 3/4. We also know that the prey density will be approximately described by the Sheldon power law, i.e., that <span class="math inline">\(N(w) = N_0\ w^{-\lambda}\)</span> with <span class="math inline">\(\lambda\)</span>. A bit of maths then says that <span class="math display">\[q = 2 - \lambda + n\]</span> This explains the message you got when you created the params object with a certain choice of <span class="math inline">\(\lambda\)</span>: mizer chose the search volume exponent automtically according to this formula. In the real world evolution will have made sure that the fish will have developed a feeding strategy that allows it to cover its metabolic costs, and thus leads to that search volume exponent of <span class="math inline">\(q\)</span>. Clearly filter feeders have taken a very different route to this than forage fish, but the result is the same.</p>
<p>Let us see what effect changing the coefficient <span class="math inline">\(\gamma_0\)</span> in the search volume rate has. Its current value in our model is</p>
<div class="sourceCode" id="cb70"><html><body><pre class="r"><span class="no">params</span>@<span class="kw">species_params</span>$<span class="no">gamma</span></pre></body></html></div>
<pre><code>## [1] 3686.147</code></pre>
<p>We change that with <code>setSearchVolume()</code> and find the new steady state.</p>
<div class="sourceCode" id="cb72"><html><body><pre class="r"><span class="no">params_new_gamma</span> <span class="kw">&lt;-</span> <span class="no">params</span>
<span class="no">params_new_gamma</span>@<span class="kw">species_params</span>$<span class="no">gamma</span> <span class="kw">&lt;-</span> <span class="fl">2000</span>
<span class="no">params_new_gamma</span> <span class="kw">&lt;-</span> <span class="fu">setSearchVolume</span>(<span class="no">params_new_gamma</span>) <span class="kw">%&gt;%</span>
  <span class="fu">steady</span>()</pre></body></html></div>
<pre><code>## Steady state was reached before 7.5 years.</code></pre>
<p>We can see the effect in the growth curve of our species. In the original model it looks as follows:</p>
<div class="sourceCode" id="cb74"><html><body><pre class="r"><span class="fu">plotGrowthCurves</span>(<span class="no">params</span>, <span class="kw">species</span> <span class="kw">=</span> <span class="st">"1"</span>)</pre></body></html></div>
<p><img src="single_species_size-spectrum_dynamics_files/figure-html/unnamed-chunk-52-1.png" width="700"></p>
<p>In the modified model it looks like</p>
<div class="sourceCode" id="cb75"><html><body><pre class="r"><span class="fu">plotGrowthCurves</span>(<span class="no">params_new_gamma</span>, <span class="kw">species</span> <span class="kw">=</span> <span class="st">"1"</span>)</pre></body></html></div>
<p><img src="single_species_size-spectrum_dynamics_files/figure-html/unnamed-chunk-53-1.png" width="700"></p>
</div>
<div id="exercise-7" class="section level2">
<h2 class="hasAnchor">
<a href="#exercise-7" class="anchor"></a>Exercise 7</h2>
<p>What effect will this change in growth rate have on the slope of the juvenile spectrum? Will it be steeper or shallower? Make the plot of the spectrum to see.</p>
</div>
<div id="feeding-level" class="section level2">
<h2 class="hasAnchor">
<a href="#feeding-level" class="anchor"></a>Feeding level</h2>
<p>A predator will have a maximum intake rate. It will simple not be able to utilise food at a faster rate than its maximum intake rate. Of course in practice it will not feed at the maximum intake rate because of limited availability of prey. We describe this by the <em>feeding level</em> which is the proportion of its maximum intake rate at which the predator is actually taking in prey.</p>
<p>In our simple model this feeding level is constant.</p>
<div class="sourceCode" id="cb76"><html><body><pre class="r"><span class="fu">plotFeedingLevel</span>(<span class="no">params</span>)</pre></body></html></div>
<p><img src="single_species_size-spectrum_dynamics_files/figure-html/unnamed-chunk-54-1.png" width="700"></p>
<p>In the model with the reduced search volume the feeding level will be lower</p>
<div class="sourceCode" id="cb77"><html><body><pre class="r"><span class="fu">plotFeedingLevel</span>(<span class="no">params_new_gamma</span>)</pre></body></html></div>
<p><img src="single_species_size-spectrum_dynamics_files/figure-html/unnamed-chunk-55-1.png" width="700"></p>
<p>Our model is taking an allometric form for the maximum intake rate <span class="math inline">\(h(w)\)</span> as a function of predator size <span class="math inline">\(w\)</span>: <span class="math inline">\(h(w) = h\ w^n\)</span>. The current value of the coefficient <span class="math inline">\(h\)</span> is</p>
<div class="sourceCode" id="cb78"><html><body><pre class="r"><span class="no">params</span>@<span class="kw">species_params</span>$<span class="no">h</span></pre></body></html></div>
<pre><code>## [1] 51.6855</code></pre>
<p>We can change the maximum intake rate with <code>setIntakeMax()</code>.</p>
</div>
</div>
<div id="mortality" class="section level1">
<h1 class="hasAnchor">
<a href="#mortality" class="anchor"></a>Mortality</h1>
<div id="death-from-predation" class="section level2">
<h2 class="hasAnchor">
<a href="#death-from-predation" class="anchor"></a>Death from predation</h2>
<p>Of course growth of the predator is only one aspect of predation. The other is the death of the prey. Growth and mortality are coupled. Increased growth of one class of individuals will necessitate increased death of another. There is no free lunch.</p>
<p>Once we have specified the predation parameters, these parameters determine both the growth of predators but also the mortality rate of prey. So we don’t have to introduce new paramters in this section.</p>
</div>
<div id="background-mortality" class="section level2">
<h2 class="hasAnchor">
<a href="#background-mortality" class="anchor"></a>Background mortality</h2>
<p>In addition to mortality caused by predation from other fish, there will be some mortality from other causes. This could be predation from animals that we have not included in our model, like sea birds or mamals, or it could be death from old age (senescent death) or disease. Mizer allows setting of background death with <code>setBMort()</code>.</p>
</div>
</div>
<div id="fishing-mortality" class="section level1">
<h1 class="hasAnchor">
<a href="#fishing-mortality" class="anchor"></a>Fishing mortality</h1>
<p>The cause of mortality that is most under our control is mortality from fishing. You can see how fishing is set up in mizer at <a href="https://sizespectrum.org/mizer/dev/reference/setFishing.html#setting-fishing" class="uri">https://sizespectrum.org/mizer/dev/reference/setFishing.html#setting-fishing</a>. Here we only look at a simple example: we introduce fishing on our species only for fish above 30 grams. All fish greater than 30 grams will be exposed to the same fishing mortality. We call this kind of fishing selectivity “knife_edge” selectivity. Mizer can deal with more general selectivity curves, like sigmoidal or doubly sigmoidal.</p>
<div class="sourceCode" id="cb80"><html><body><pre class="r"><span class="no">params_fishing</span> <span class="kw">&lt;-</span> <span class="no">params</span>
<span class="no">params_fishing</span>@<span class="kw">species_params</span>$<span class="no">sel_func</span> <span class="kw">&lt;-</span> <span class="st">"knife_edge"</span>
<span class="no">params_fishing</span>@<span class="kw">species_params</span>$<span class="no">knife_edge_size</span> <span class="kw">&lt;-</span> <span class="fl">30</span>
<span class="no">params_fishing</span> <span class="kw">&lt;-</span> <span class="fu">setFishing</span>(<span class="no">params_fishing</span>)</pre></body></html></div>
<p>We now need to specify the fishing effort and can then find and plot the steady state</p>
<div class="sourceCode" id="cb81"><html><body><pre class="r"><span class="no">params_fishing</span>@<span class="kw">initial_effort</span> <span class="kw">&lt;-</span> <span class="fl">1</span>
<span class="no">params_fishing</span> <span class="kw">&lt;-</span> <span class="fu">steady</span>(<span class="no">params_fishing</span>)</pre></body></html></div>
<pre><code>## Steady state was reached before 4.5 years.</code></pre>
<div class="sourceCode" id="cb83"><html><body><pre class="r"><span class="fu">plotSpectra</span>(<span class="no">params_fishing</span>, <span class="kw">power</span> <span class="kw">=</span> <span class="fl">2</span>)</pre></body></html></div>
<p><img src="single_species_size-spectrum_dynamics_files/figure-html/unnamed-chunk-58-1.png" width="700"></p>
</div>
<div id="outlook" class="section level1">
<h1 class="hasAnchor">
<a href="#outlook" class="anchor"></a>Outlook</h1>
<p>The fish species we have studied had unlimited food and constant mortality. That of course is very unrealistic. In reality, food will become scarce when the fish population increases too much. Also the number of predators will grow. This will lead to interesting and important non-linear effects that we will study in the next tutorial notebook.</p>
</div>
  </div>

  <div class="col-md-3 hidden-xs hidden-sm" id="pkgdown-sidebar">

        <nav id="toc" data-toggle="toc"><h2 data-toc-skip>Contents</h2>
    </nav>
</div>

</div>



      <footer><div class="copyright">
  <p>Developed by Gustav Delius.</p>
</div>

<div class="pkgdown">
  <p>Site built with <a href="https://pkgdown.r-lib.org/">pkgdown</a> 1.5.1.9000.</p>
</div>

      </footer>
</div>

  


  </body>
</html>
